from tkinter import *
from datetime import date

def Age(birthYear, birthMonth, birthDay):
    today = date.today()
    return today.year - birthYear - ((today.month, today.day) < (birthMonth, birthDay))

class App(Frame):

    def __init__(self, tt):
        self.win = tt
        self.win.title('FC Real Madrid 2020')
        super().__init__(self.win)
        self.grid()
        self.Main()
        return

    def Main(self):
        self.b1 = Button(self, text='Players', command=self.Players)
        self.b1.grid(row=1, column=1)
        self.b2 = Button(self, text='Coaches', command=self.Coaches)
        self.b2.grid(row=2, column=1)
        self.b3 = Button(self, text='Games', command=self.Games)
        self.b3.grid(row=3, column=1)
        self.b4 = Button(self, text='Search', command=self.Search)
        self.b4.grid(row=4, column=1)
        return

    def Back(self):
        self.top.destroy()
        self.win.deiconify()
        return

    def Players(self):
        self.win.withdraw()
        self.top = Toplevel()
        self.top.title('Players')
        self.top.b1igr = Button(self.top, text='Areola', command=self.A1)
        self.top.b1igr.grid(sticky=W, row=2, column=1)
        self.top.b2igr = Button(self.top, text='Courtois', command=self.C13)
        self.top.b2igr.grid(sticky=E, row=2, column=2)
        self.top.b3igr = Button(self.top, text='Carvajal', command=self.C2)
        self.top.b3igr.grid(sticky=W, row=3, column=1)
        self.top.b4igr = Button(self.top, text='E. Militão', command=self.M3)
        self.top.b4igr.grid(sticky=E, row=3, column=2)
        self.top.b5igr = Button(self.top, text='Sergio Ramos', command=self.SR4)
        self.top.b5igr.grid(sticky=W, row=4, column=1)
        self.top.b6igr = Button(self.top, text='R. Varane', command=self.V5)
        self.top.b6igr.grid(sticky=E, row=4, column=2)
        self.top.b7igr = Button(self.top, text='Nacho', command=self.N6)
        self.top.b7igr.grid(sticky=W, row=5, column=1)
        self.top.b8igr = Button(self.top, text='Marcelo', command=self.M12)
        self.top.b8igr.grid(sticky=E, row=5, column=2)
        self.top.b9igr = Button(self.top, text='F. Mendy', command=self.M23)
        self.top.b9igr.grid(sticky=W, row=6, column=1)
        self.top.b10igr = Button(self.top, text='Kroos', command=self.K8)
        self.top.b10igr.grid(sticky=E, row=6, column=2)
        self.top.b11igr = Button(self.top, text='Modrić', command=self.M10)
        self.top.b11igr.grid(sticky=W, row=7, column=1)
        self.top.b12igr = Button(self.top, text='Casemiro', command=self.C14)
        self.top.b12igr.grid(sticky=E, row=7, column=2)
        self.top.b13igr = Button(self.top, text='Valverde', command=self.V15)
        self.top.b13igr.grid(sticky=W, row=8, column=1)
        self.top.b14igr = Button(self.top, text='James Rodríguez', command=self.JR16)
        self.top.b14igr.grid(sticky=E, row=8, column=2)
        self.top.b15igr = Button(self.top, text='Isco', command=self.I22)
        self.top.b15igr.grid(sticky=W, row=9, column=1)
        self.top.b16igr = Button(self.top, text='Hazard', command=self.H7)
        self.top.b16igr.grid(sticky=E, row=9, column=2)
        self.top.b17igr = Button(self.top, text='Benzema', command=self.B9)
        self.top.b17igr.grid(sticky=W, row=10, column=1)
        self.top.b18igr = Button(self.top, text='Bale', command=self.B11)
        self.top.b18igr.grid(sticky=E, row=10, column=2)
        self.top.b19igr = Button(self.top, text='Lucas Vázquez', command=self.LV17)
        self.top.b19igr.grid(sticky=W, row=11, column=1)
        self.top.b20igr = Button(self.top, text='Jović', command=self.J18)
        self.top.b20igr.grid(sticky=E, row=11, column=2)
        self.top.b21igr = Button(self.top, text='Asensio', command=self.A20)
        self.top.b21igr.grid(sticky=W, row=12, column=1)
        self.top.b22igr = Button(self.top, text='Brahim', command=self.B21)
        self.top.b22igr.grid(sticky=E, row=12, column=2)
        self.top.b23igr = Button(self.top, text='Mariano', command=self.M24)
        self.top.b23igr.grid(sticky=W, row=13, column=1)
        self.top.b24igr = Button(self.top, text='Vinicius Junior', command=self.VJ25)
        self.top.b24igr.grid(sticky=E, row=13, column=2)
        self.top.b25igr = Button(self.top, text='Rodrygo', command=self.R27)
        self.top.b25igr.grid(sticky=W, row=14, column=1)
        self.top.l1igr = Label(self.top, text='   ')
        self.top.l1igr.grid(row=0, column=3)
        self.top.bigpovr = Button(self.top, text='Back to Main menu', command=self.Back)
        self.top.bigpovr.grid(row=7, column=4)
        return

    def Coaches(self):
        self.win.withdraw()
        self.top = Toplevel()
        self.top.title('Coaches')
        self.top.bospovr = Button(self.top, text='Back to Main menu', command=self.Back)
        self.top.bospovr.grid(row=0, column=1)
        self.top.l2os = Label(self.top, text='Zinedine Zidane')
        self.top.l2os.grid(row=1, column=1)
        self.top.l3os = Label(self.top, text='David Bettoni')
        self.top.l3os.grid(row=2, column=1)
        self.top.l4os = Label(self.top, text='Hamidou Msaidie')
        self.top.l4os.grid(row=3, column=1)
        self.top.l5os = Label(self.top, text='Grégory Dupont')
        self.top.l5os.grid(row=1, column=2)
        self.top.l6os = Label(self.top, text='Eoberto Vázquez')
        self.top.l6os.grid(row=2, column=2)
        self.top.l6os = Label(self.top, text='Javier Mallo')
        self.top.l6os.grid(row=3, column=2)
        self.top.l6os = Label(self.top, text='José Carlos G. Parrales')
        self.top.l6os.grid(row=4, column=2)
        return

    def Games(self):
        self.win.withdraw()
        self.top = Toplevel()
        self.top.title('Games')
        self.top.butpovr = Button(self.top, text='Back to Main menu', command=self.Back)
        self.top.butpovr.grid(row=0, column=0)
        self.top.l1ut = Label(self.top, text='Upcoming games:')
        self.top.l1ut.grid(row=1, column=0)
        self.top.l2ut = Label(self.top, text='Postponed')
        self.top.l2ut.grid(row=2, column=0)
        self.top.l3ut = Label(self.top, text='Real Madrid-Éibar')
        self.top.l3ut.grid(row=2, column=1)
        self.top.l4ut = Label(self.top, text='Postponed')
        self.top.l4ut.grid(row=3, column=0)
        self.top.l5ut = Label(self.top, text='Manchester City-Real Madrid')
        self.top.l5ut.grid(row=3, column=1)
        self.top.l6ut = Label(self.top, text='Postponed')
        self.top.l6ut.grid(row=4, column=0)
        self.top.l7ut = Label(self.top, text='Real Madrid-Valencia')
        self.top.l7ut.grid(row=4, column=1)
        self.top.l8ut = Label(self.top, text='Postponed')
        self.top.l8ut.grid(row=5, column=0)
        self.top.l9ut = Label(self.top, text='Real Sociedad-Real Madrid')
        self.top.l9ut.grid(row=5, column=1)
        self.top.l10ut = Label(self.top, text='Postponed')
        self.top.l10ut.grid(row=6, column=0)
        self.top.l11ut = Label(self.top, text='Real Madrid-Mallorca')
        self.top.l11ut.grid(row=6, column=1)
        self.top.l12ut = Label(self.top, text='Postponed')
        self.top.l12ut.grid(row=7, column=0)
        self.top.l13ut = Label(self.top, text='Espanyol-Real Madrid')
        self.top.l13ut.grid(row=7, column=1)
        self.top.l14ut = Label(self.top, text='Postponed')
        self.top.l14ut.grid(row=8, column=0)
        self.top.l15ut = Label(self.top, text='Real Madrid-Getafe')
        self.top.l15ut.grid(row=8, column=1)
        self.top.l16ut = Label(self.top, text='Postponed')
        self.top.l16ut.grid(row=9, column=0)
        self.top.l17ut = Label(self.top, text='Athletic Club-Real Madrid')
        self.top.l17ut.grid(row=9, column=1)
        self.top.l18ut = Label(self.top, text='Postponed')
        self.top.l18ut.grid(row=10, column=0)
        self.top.l19ut = Label(self.top, text='Real Madrid-Alavés')
        self.top.l19ut.grid(row=10, column=1)
        self.top.l20ut = Label(self.top, text='Postponed')
        self.top.l20ut.grid(row=11, column=0)
        self.top.l21ut = Label(self.top, text='Granada-Real Madrid')
        self.top.l21ut.grid(row=11, column=1)
        self.top.l22ut = Label(self.top, text='Postponed')
        self.top.l22ut.grid(row=12, column=0)
        self.top.l23ut = Label(self.top, text='Real Madrid-Villarreal')
        self.top.l23ut.grid(row=12, column=1)
        self.top.l24ut = Label(self.top, text='Postponed')
        self.top.l24ut.grid(row=13, column=0)
        self.top.l25ut = Label(self.top, text='Leganés-Real Madrid')
        self.top.l25ut.grid(row=13, column=1)
        self.top.b1ut = Button(self.top, text='Previous games', command=self.Previous)
        self.top.b1ut.grid(row=14, column=0)
        return

    def Search(self):
        self.win.withdraw()
        self.top = Toplevel()
        self.top.title('Search')
        self.top.bpretpovr = Button(self.top, text='Back to Main menu', command=self.Back)
        self.top.bpretpovr.grid(row=0, column=0)
        self.top.l1pret = Label(self.top, text='Enter first and/or last name of the player you want to find')
        self.top.l1pret.grid(row=1, column=0)
        self.top.e1pret = Entry(self.top)
        self.top.e1pret.grid(row=1, column=1)
        self.top.b1pret = Button(self.top, text='Search', command=self.Find)
        self.top.b1pret.grid(row=2, column=1)
        self.top.l1nadi = Label(self.top, text='')
        self.top.l1nadi.grid(row=2, column=3)
        return

    def Previous(self):
        self.top.l1pr = Label(self.top, text='Games from the beginning of 2020')
        self.top.l1pr.grid(row=15, column=0)
        self.top.l2pr = Label(self.top, text='Saturday, 04/01')
        self.top.l2pr.grid(row=16, column=0)
        self.top.l3pr = Label(self.top, text='Getafe-Real Madrid')
        self.top.l3pr.grid(row=16, column=1)
        self.top.l4pr = Label(self.top, text='0-3')
        self.top.l4pr.grid(row=16, column=2)
        self.top.l5pr = Label(self.top, text='Wednesday, 08/01')
        self.top.l5pr.grid(row=17, column=0)
        self.top.l6pr = Label(self.top, text='Valencia-Real Madrid')
        self.top.l6pr.grid(row=17, column=1)
        self.top.l7pr = Label(self.top, text='1-3')
        self.top.l7pr.grid(row=17, column=2)
        self.top.l8pr = Label(self.top, text='Sunday, 12/01')
        self.top.l8pr.grid(row=18, column=0)
        self.top.l9pr = Label(self.top, text='Real Madrid-Atlético')
        self.top.l9pr.grid(row=18, column=1)
        self.top.l10pr = Label(self.top, text='0-0')
        self.top.l10pr.grid(row=18, column=2)
        self.top.l11pr = Label(self.top, text='Saturday, 18/01')
        self.top.l11pr.grid(row=19, column=0)
        self.top.l12pr = Label(self.top, text='Real Madrid-Sevilla')
        self.top.l12pr.grid(row=19, column=1)
        self.top.l13pr = Label(self.top, text='2-1')
        self.top.l13pr.grid(row=19, column=2)
        self.top.l14pr = Label(self.top, text='Wednesday, 22/01')
        self.top.l14pr.grid(row=20, column=0)
        self.top.l15pr = Label(self.top, text='Unionistas de Salamanca-Real Madrid')
        self.top.l15pr.grid(row=20, column=1)
        self.top.l16pr = Label(self.top, text='1-3')
        self.top.l16pr.grid(row=20, column=2)
        self.top.l17pr = Label(self.top, text='Sunday, 26/01')
        self.top.l17pr.grid(row=21, column=0)
        self.top.l18pr = Label(self.top, text='Real Valladolid-Real Madrid')
        self.top.l18pr.grid(row=21, column=1)
        self.top.l19pr = Label(self.top, text='0-1')
        self.top.l19pr.grid(row=21, column=2)
        self.top.l20pr = Label(self.top, text='Wednesday, 29/01')
        self.top.l20pr.grid(row=22, column=0)
        self.top.l21pr = Label(self.top, text='Real Zaragoza-Real Madrid')
        self.top.l21pr.grid(row=22, column=1)
        self.top.l22pr = Label(self.top, text='0-4')
        self.top.l22pr.grid(row=22, column=2)
        self.top.l23pr = Label(self.top, text='Saturday, 01/02')
        self.top.l23pr.grid(row=23, column=0)
        self.top.l24pr = Label(self.top, text='Real Madrid-Atlético')
        self.top.l24pr.grid(row=23, column=1)
        self.top.l25pr = Label(self.top, text='1-0')
        self.top.l25pr.grid(row=23, column=2)
        self.top.l26pr = Label(self.top, text='Thursday, 06/02')
        self.top.l26pr.grid(row=24, column=0)
        self.top.l27pr = Label(self.top, text='Real Madrid-Real Sociedad')
        self.top.l27pr.grid(row=24, column=1)
        self.top.l28pr = Label(self.top, text='3-4')
        self.top.l28pr.grid(row=24, column=2)
        self.top.l29pr = Label(self.top, text='Sunday, 09/02')
        self.top.l29pr.grid(row=25, column=0)
        self.top.l30pr = Label(self.top, text='Osasuna-Real Madrid')
        self.top.l30pr.grid(row=25, column=1)
        self.top.l31pr = Label(self.top, text='1-4')
        self.top.l31pr.grid(row=25, column=2)
        self.top.l32pr = Label(self.top, text='Sunday, 16/02')
        self.top.l32pr.grid(row=26, column=0)
        self.top.l33pr = Label(self.top, text='Real Madrid-Celta de Vigo')
        self.top.l33pr.grid(row=26, column=1)
        self.top.l34pr = Label(self.top, text='2-2')
        self.top.l34pr.grid(row=26, column=2)
        self.top.l35pr = Label(self.top, text='Saturday, 22/02')
        self.top.l35pr.grid(row=27, column=0)
        self.top.l36pr = Label(self.top, text='Levante-Real Madrid')
        self.top.l36pr.grid(row=27, column=1)
        self.top.l37pr = Label(self.top, text='1-0')
        self.top.l37pr.grid(row=27, column=2)
        self.top.l38pr = Label(self.top, text='Wednesday, 26/02')
        self.top.l38pr.grid(row=28, column=0)
        self.top.l39pr = Label(self.top, text='Real Madrid-Manchester City')
        self.top.l39pr.grid(row=28, column=1)
        self.top.l40pr = Label(self.top, text='1-2')
        self.top.l40pr.grid(row=28, column=2)
        self.top.l41pr = Label(self.top, text='Sunday, 01/03')
        self.top.l41pr.grid(row=29, column=0)
        self.top.l42pr = Label(self.top, text='Real Madrid-Barcelona')
        self.top.l42pr.grid(row=29, column=1)
        self.top.l43pr = Label(self.top, text='2-0')
        self.top.l43pr.grid(row=29, column=2)
        self.top.l44pr = Label(self.top, text='Sunday, 08/03')
        self.top.l44pr.grid(row=30, column=0)
        self.top.l45pr = Label(self.top, text='Betis-Real Madrid')
        self.top.l45pr.grid(row=30, column=1)
        self.top.l46pr = Label(self.top, text='2-1')
        self.top.l46pr.grid(row=30, column=2)
        return

    def A1(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Alphonse Areola')
        self.top.l1A1 = Label(self.top, text='Name: Alphonse Areola')
        self.top.l1A1.grid(sticky=N, row=0, column=2)
        self.top.l2A1 = Label(self.top, text='Place of birth: Paris, France')
        self.top.l2A1.grid(sticky=W, row=2, column=1)
        self.top.l3A1 = Label(self.top, text='Date of birth: 27/02/1993')
        self.top.l3A1.grid(sticky=W, row=3, column=1)
        self.top.l4A1 = Label(self.top, text='Age: ' + str(Age(1993, 2, 27)))
        self.top.l4A1.grid(sticky=W, row=4, column=1)
        self.top.l5A1 = Label(self.top, text='Team member since 2019')
        self.top.l5A1.grid(sticky=W, row=5, column=1)
        self.top.l6A1 = Label(self.top, text='Height: 1.95 m')
        self.top.l6A1.grid(sticky=W, row=2, column=3)
        self.top.l7A1 = Label(self.top, text='Weight: 94 kg')
        self.top.l7A1.grid(sticky=W, row=3, column=3)
        self.top.l8A1 = Label(self.top, text='Number: 1')
        self.top.l8A1.grid(sticky=W, row=4, column=3)
        self.top.l9A1 = Label(self.top, text='Position: goalkeeper')
        self.top.l9A1.grid(sticky=W, row=5, column=3)
        self.top.l10A1 = Label(self.top, text='                       ')
        self.top.l10A1.grid(sticky=W, row=0, column=4)
        self.top.b1A1 = Button(self.top, text='Statistics', command=self.StatA1)
        self.top.b1A1.grid(sticky=E, row=1, column=5)
        self.top.bA1povr = Button(self.top, text='Back', command=self.Back)
        self.top.bA1povr.grid(sticky=W, row=1, column=1)
        return

    def StatA1(self):
        self.top.l1SA1 = Label(self.top, text='Appearances: 8')
        self.top.l1SA1.grid(sticky=E, row=2, column=5)
        self.top.l2SA1 = Label(self.top, text='Conceded goals: 9')
        self.top.l2SA1.grid(sticky=E, row=3, column=5)
        self.top.l3SA1 = Label(self.top, text='Goals saved: 13')
        self.top.l3SA1.grid(sticky=E, row=4, column=5)
        return

    def C13(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Thibaut Courtois')
        self.top.l1C13 = Label(self.top, text='Name: Thibaut Courtois')
        self.top.l1C13.grid(sticky=N, row=0, column=2)
        self.top.l2C13 = Label(self.top, text='Place of birth: Bree, Belgium')
        self.top.l2C13.grid(sticky=W, row=2, column=1)
        self.top.l3C13 = Label(self.top, text='Date of birth: 11/05/1992')
        self.top.l3C13.grid(sticky=W, row=3, column=1)
        self.top.l4C13 = Label(self.top, text='Age: ' + str(Age(1992, 5, 11)))
        self.top.l4C13.grid(sticky=W, row=4, column=1)
        self.top.l5C13 = Label(self.top, text='Team member since 2018')
        self.top.l5C13.grid(sticky=W, row=5, column=1)
        self.top.l6C13 = Label(self.top, text='Height: 1.99 m')
        self.top.l6C13.grid(sticky=W, row=2, column=3)
        self.top.l7C13 = Label(self.top, text='Weight: 96 kg')
        self.top.l7C13.grid(sticky=W, row=3, column=3)
        self.top.l8C13 = Label(self.top, text='Number: 13')
        self.top.l8C13.grid(sticky=W, row=4, column=3)
        self.top.l9C13 = Label(self.top, text='Position: goalkeeper')
        self.top.l9C13.grid(sticky=W, row=5, column=3)
        self.top.l10C13 = Label(self.top, text='                       ')
        self.top.l10C13.grid(sticky=W, row=0, column=4)
        self.top.b1C13 = Button(self.top, text='Statistics', command=self.StatC13)
        self.top.b1C13.grid(sticky=E, row=1, column=5)
        self.top.bC13povr = Button(self.top, text='Back', command=self.Back)
        self.top.bC13povr.grid(sticky=W, row=1, column=1)
        return

    def StatC13(self):
        self.top.l1SC13 = Label(self.top, text='Appearances: 32')
        self.top.l1SC13.grid(sticky=E, row=2, column=5)
        self.top.l2SC13 = Label(self.top, text='Conceded goals: 26')
        self.top.l2SC13.grid(sticky=E, row=3, column=5)
        self.top.l3SC13 = Label(self.top, text='Goals saved: 71')
        self.top.l3SC13.grid(sticky=E, row=4, column=5)
        return

    def C2(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Daniel Carvajal Ramos')
        self.top.l1C2 = Label(self.top, text='Name: Daniel Carvajal Ramos')
        self.top.l1C2.grid(sticky=N, row=0, column=2)
        self.top.l2C2 = Label(self.top, text='Place of birth: Leganés, Madrid')
        self.top.l2C2.grid(sticky=W, row=2, column=1)
        self.top.l3C2 = Label(self.top, text='Date of birth: 11/01/1992')
        self.top.l3C2.grid(sticky=W, row=3, column=1)
        self.top.l4C2 = Label(self.top, text='Age: ' + str(Age(1992, 1, 11)))
        self.top.l4C2.grid(sticky=W, row=4, column=1)
        self.top.l5C2 = Label(self.top, text='Team member since 2013')
        self.top.l5C2.grid(sticky=W, row=5, column=1)
        self.top.l6C2 = Label(self.top, text='Height: 1.73 m')
        self.top.l6C2.grid(sticky=W, row=2, column=3)
        self.top.l7C2 = Label(self.top, text='Weight: 73.5 kg')
        self.top.l7C2.grid(sticky=W, row=3, column=3)
        self.top.l8C2 = Label(self.top, text='Number: 2')
        self.top.l8C2.grid(sticky=W, row=4, column=3)
        self.top.l9C2 = Label(self.top, text='Position: defender')
        self.top.l9C2.grid(sticky=W, row=5, column=3)
        self.top.l10C2 = Label(self.top, text='                       ')
        self.top.l10C2.grid(sticky=W, row=0, column=4)
        self.top.b1C2 = Button(self.top, text='Statistics', command=self.StatC2)
        self.top.b1C2.grid(sticky=E, row=1, column=5)
        self.top.bC2povr = Button(self.top, text='Back', command=self.Back)
        self.top.bC2povr.grid(sticky=W, row=1, column=1)
        return

    def StatC2(self):
        self.top.l1SC2 = Label(self.top, text='Appearances: 32')
        self.top.l1SC2.grid(sticky=E, row=2, column=5)
        self.top.l2SC2 = Label(self.top, text='Goals: 1')
        self.top.l2SC2.grid(sticky=E, row=3, column=5)
        self.top.l3SC2 = Label(self.top, text='Assistance: 7')
        self.top.l3SC2.grid(sticky=E, row=4, column=5)
        return

    def M3(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Éder Gabriel Militão')
        self.top.l1M3 = Label(self.top, text='Name: Éder Gabriel Militão')
        self.top.l1M3.grid(sticky=N, row=0, column=2)
        self.top.l2M3 = Label(self.top, text='Place of birth: Sertãozinho, Brasil')
        self.top.l2M3.grid(sticky=W, row=2, column=1)
        self.top.l3M3 = Label(self.top, text='Date of birth: 18/01/1998')
        self.top.l3M3.grid(sticky=W, row=3, column=1)
        self.top.l4M3 = Label(self.top, text='Age: ' + str(Age(1998, 1, 18)))
        self.top.l4M3.grid(sticky=W, row=4, column=1)
        self.top.l5M3 = Label(self.top, text='Team member since 2019')
        self.top.l5M3.grid(sticky=W, row=5, column=1)
        self.top.l6M3 = Label(self.top, text='Height: 1.86 m')
        self.top.l6M3.grid(sticky=W, row=2, column=3)
        self.top.l7M3 = Label(self.top, text='Weight: 78 kg')
        self.top.l7M3.grid(sticky=W, row=3, column=3)
        self.top.l8M3 = Label(self.top, text='Number: 3')
        self.top.l8M3.grid(sticky=W, row=4, column=3)
        self.top.l9M3 = Label(self.top, text='Position: defender')
        self.top.l9M3.grid(sticky=W, row=5, column=3)
        self.top.l10M3 = Label(self.top, text='                       ')
        self.top.l10M3.grid(sticky=W, row=0, column=4)
        self.top.b1M3 = Button(self.top, text='Statistics', command=self.StatM3)
        self.top.b1M3.grid(sticky=E, row=1, column=5)
        self.top.bM3povr = Button(self.top, text='Back', command=self.Back)
        self.top.bM3povr.grid(sticky=W, row=1, column=1)
        return

    def StatM3(self):
        self.top.l1SM3 = Label(self.top, text='Appearances: 13')
        self.top.l1SM3.grid(sticky=E, row=2, column=5)
        self.top.l2SM3 = Label(self.top, text='Goals: 0')
        self.top.l2SM3.grid(sticky=E, row=3, column=5)
        self.top.l3SM3 = Label(self.top, text='Assistance: 0')
        self.top.l3SM3.grid(sticky=E, row=4, column=5)
        return

    def SR4(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Sergio Ramos García')
        self.top.l1SR4 = Label(self.top, text='Name: Sergio Ramos García')
        self.top.l1SR4.grid(sticky=N, row=0, column=2)
        self.top.l2SR4 = Label(self.top, text='Place of birth: Camas, Spain')
        self.top.l2SR4.grid(sticky=W, row=2, column=1)
        self.top.l3SR4 = Label(self.top, text='Date of birth: 30/03/1986')
        self.top.l3SR4.grid(sticky=W, row=3, column=1)
        self.top.l4SR4 = Label(self.top, text='Age: ' + str(Age(1986, 3, 30)))
        self.top.l4SR4.grid(sticky=W, row=4, column=1)
        self.top.l5SR4 = Label(self.top, text='Team member since 2005')
        self.top.l5SR4.grid(sticky=W, row=5, column=1)
        self.top.l6SR4 = Label(self.top, text='Height: 1.84 m')
        self.top.l6SR4.grid(sticky=W, row=2, column=3)
        self.top.l7SR4 = Label(self.top, text='Weight: 82.2 kg')
        self.top.l7SR4.grid(sticky=W, row=3, column=3)
        self.top.l8SR4 = Label(self.top, text='Number: 4')
        self.top.l8SR4.grid(sticky=W, row=4, column=3)
        self.top.l9SR4 = Label(self.top, text='Position: defender')
        self.top.l9SR4.grid(sticky=W, row=5, column=3)
        self.top.l10SR4 = Label(self.top, text='                       ')
        self.top.l10SR4.grid(sticky=W, row=0, column=4)
        self.top.b1SR4 = Button(self.top, text='Statistics', command=self.StatSR4)
        self.top.b1SR4.grid(sticky=E, row=1, column=5)
        self.top.bSR4povr = Button(self.top, text='Back', command=self.Back)
        self.top.bSR4povr.grid(sticky=W, row=1, column=1)
        return

    def StatSR4(self):
        self.top.l1SSR4 = Label(self.top, text='Appearances: 34')
        self.top.l1SSR4.grid(sticky=E, row=2, column=5)
        self.top.l2SSR4 = Label(self.top, text='Goals: 7')
        self.top.l2SSR4.grid(sticky=E, row=3, column=5)
        self.top.l3SSR4 = Label(self.top, text='Assistance: 0')
        self.top.l3SSR4.grid(sticky=E, row=4, column=5)
        return

    def V5(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Raphaël Varane')
        self.top.l1V5 = Label(self.top, text='Name: Raphaël Varane')
        self.top.l1V5.grid(sticky=N, row=0, column=2)
        self.top.l2V5 = Label(self.top, text='Place of birth: Lille, France')
        self.top.l2V5.grid(sticky=W, row=2, column=1)
        self.top.l3V5 = Label(self.top, text='Date of birth: 25/04/1993')
        self.top.l3V5.grid(sticky=W, row=3, column=1)
        self.top.l4V5 = Label(self.top, text='Age: ' + str(Age(1993, 4, 25)))
        self.top.l4V5.grid(sticky=W, row=4, column=1)
        self.top.l5V5 = Label(self.top, text='Team member since 2011')
        self.top.l5V5.grid(sticky=W, row=5, column=1)
        self.top.l6V5 = Label(self.top, text='Height: 1.91 m')
        self.top.l6V5.grid(sticky=W, row=2, column=3)
        self.top.l7V5 = Label(self.top, text='Weight: 81.2 kg')
        self.top.l7V5.grid(sticky=W, row=3, column=3)
        self.top.l8V5 = Label(self.top, text='Number: 5')
        self.top.l8V5.grid(sticky=W, row=4, column=3)
        self.top.l9V5 = Label(self.top, text='Position: defender')
        self.top.l9V5.grid(sticky=W, row=5, column=3)
        self.top.l10V5 = Label(self.top, text='                       ')
        self.top.l10V5.grid(sticky=W, row=0, column=4)
        self.top.b1V5 = Button(self.top, text='Statistics', command=self.StatV5)
        self.top.b1V5.grid(sticky=E, row=1, column=5)
        self.top.bV5povr = Button(self.top, text='Back', command=self.Back)
        self.top.bV5povr.grid(sticky=W, row=1, column=1)
        return

    def StatV5(self):
        self.top.l1SV5 = Label(self.top, text='Appearances: 33')
        self.top.l1SV5.grid(sticky=E, row=2, column=5)
        self.top.l2SV5 = Label(self.top, text='Goals: 3')
        self.top.l2SV5.grid(sticky=E, row=3, column=5)
        self.top.l3SV5 = Label(self.top, text='Assistance: 1')
        self.top.l3SV5.grid(sticky=E, row=4, column=5)
        return

    def N6(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Nacho')
        self.top.l1N6 = Label(self.top, text='Name: José I. Fernández Iglesias')
        self.top.l1N6.grid(sticky=N, row=0, column=2)
        self.top.l2N6 = Label(self.top, text='Place of birth: Madrid, Spain')
        self.top.l2N6.grid(sticky=W, row=2, column=1)
        self.top.l3N6 = Label(self.top, text='Date of birth: 18/01/1990')
        self.top.l3N6.grid(sticky=W, row=3, column=1)
        self.top.l4N6 = Label(self.top, text='Age: ' + str(Age(1990, 1, 18)))
        self.top.l4N6.grid(sticky=W, row=4, column=1)
        self.top.l5N6 = Label(self.top, text='Team member since 2012')
        self.top.l5N6.grid(sticky=W, row=5, column=1)
        self.top.l6N6 = Label(self.top, text='Height: 1.80 m')
        self.top.l6N6.grid(sticky=W, row=2, column=3)
        self.top.l7N6 = Label(self.top, text='Weight: 76.3 kg')
        self.top.l7N6.grid(sticky=W, row=3, column=3)
        self.top.l8N6 = Label(self.top, text='Number: 6')
        self.top.l8N6.grid(sticky=W, row=4, column=3)
        self.top.l9N6 = Label(self.top, text='Position: defender')
        self.top.l9N6.grid(sticky=W, row=5, column=3)
        self.top.l10N6 = Label(self.top, text='                       ')
        self.top.l10N6.grid(sticky=W, row=0, column=4)
        self.top.b1N6 = Button(self.top, text='Statistics', command=self.StatN6)
        self.top.b1N6.grid(sticky=E, row=1, column=5)
        self.top.bN6povr = Button(self.top, text='Back', command=self.Back)
        self.top.bN6povr.grid(sticky=W, row=1, column=1)
        return

    def StatN6(self):
        self.top.l1SN6 = Label(self.top, text='Appearances: 9')
        self.top.l1SN6.grid(sticky=E, row=2, column=5)
        self.top.l2SN6 = Label(self.top, text='Goals: 2')
        self.top.l2SN6.grid(sticky=E, row=3, column=5)
        self.top.l3SN6 = Label(self.top, text='Assistance: 0')
        self.top.l3SN6.grid(sticky=E, row=4, column=5)
        return

    def M12(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Marcelo Vieira da Silva')
        self.top.l1M12 = Label(self.top, text='Name: Marcelo Vieira da Silva')
        self.top.l1M12.grid(sticky=N, row=0, column=2)
        self.top.l2M12 = Label(self.top, text='Place of birth: Rio de Janeiro, Brasil')
        self.top.l2M12.grid(sticky=W, row=2, column=1)
        self.top.l3M12 = Label(self.top, text='Date of birth: 12/05/1988')
        self.top.l3M12.grid(sticky=W, row=3, column=1)
        self.top.l4M12 = Label(self.top, text='Age: ' + str(Age(1988, 5, 12)))
        self.top.l4M12.grid(sticky=W, row=4, column=1)
        self.top.l5M12 = Label(self.top, text='Team member since 2006')
        self.top.l5M12.grid(sticky=W, row=5, column=1)
        self.top.l6M12 = Label(self.top, text='Height: 1.74 m')
        self.top.l6M12.grid(sticky=W, row=2, column=3)
        self.top.l7M12 = Label(self.top, text='Weight: 75 kg')
        self.top.l7M12.grid(sticky=W, row=3, column=3)
        self.top.l8M12 = Label(self.top, text='Number: 12')
        self.top.l8M12.grid(sticky=W, row=4, column=3)
        self.top.l9M12 = Label(self.top, text='Position: defender')
        self.top.l9M12.grid(sticky=W, row=5, column=3)
        self.top.l10M12 = Label(self.top, text='                       ')
        self.top.l10M12.grid(sticky=W, row=0, column=4)
        self.top.b1M12 = Button(self.top, text='Statistics', command=self.StatM12)
        self.top.b1M12.grid(sticky=E, row=1, column=5)
        self.top.bM12povr = Button(self.top, text='Back', command=self.Back)
        self.top.bM12povr.grid(sticky=W, row=1, column=1)
        return

    def StatM12(self):
        self.top.l1SM12 = Label(self.top, text='Appearances: 19')
        self.top.l1SM12.grid(sticky=E, row=2, column=5)
        self.top.l2SM12 = Label(self.top, text='Goals: 1')
        self.top.l2SM12.grid(sticky=E, row=3, column=5)
        self.top.l3SM12 = Label(self.top, text='Assistance: 4')
        self.top.l3SM12.grid(sticky=E, row=4, column=5)
        return

    def M23(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Ferland Mendy')
        self.top.l1M23 = Label(self.top, text='Name: Ferland Mendy')
        self.top.l1M23.grid(sticky=N, row=0, column=2)
        self.top.l2M23 = Label(self.top, text='Place of birth: Meulan-en-Yvelines, France')
        self.top.l2M23.grid(sticky=W, row=2, column=1)
        self.top.l3M23 = Label(self.top, text='Date of birth: 08/06/1995')
        self.top.l3M23.grid(sticky=W, row=3, column=1)
        self.top.l4M23 = Label(self.top, text='Age: ' + str(Age(1995, 6, 8)))
        self.top.l4M23.grid(sticky=W, row=4, column=1)
        self.top.l5M23 = Label(self.top, text='Team member since 2019')
        self.top.l5M23.grid(sticky=W, row=5, column=1)
        self.top.l6M23 = Label(self.top, text='Height: 1.80 m')
        self.top.l6M23.grid(sticky=W, row=2, column=3)
        self.top.l7M23 = Label(self.top, text='Weight: 73 kg')
        self.top.l7M23.grid(sticky=W, row=3, column=3)
        self.top.l8M23 = Label(self.top, text='Number: 23')
        self.top.l8M23.grid(sticky=W, row=4, column=3)
        self.top.l9M23 = Label(self.top, text='Position: defender')
        self.top.l9M23.grid(sticky=W, row=5, column=3)
        self.top.l10M23 = Label(self.top, text='                       ')
        self.top.l10M23.grid(sticky=W, row=0, column=4)
        self.top.b1M23 = Button(self.top, text='Statistics', command=self.StatM23)
        self.top.b1M23.grid(sticky=E, row=1, column=5)
        self.top.bM23povr = Button(self.top, text='Back', command=self.Back)
        self.top.bM23povr.grid(sticky=W, row=1, column=1)
        return

    def StatM23(self):
        self.top.l1SM23 = Label(self.top, text='Appearances: 22')
        self.top.l1SM23.grid(sticky=E, row=2, column=5)
        self.top.l2SM23 = Label(self.top, text='Goals: 0')
        self.top.l2SM23.grid(sticky=E, row=3, column=5)
        self.top.l3SM23 = Label(self.top, text='Assistance: 1')
        self.top.l3SM23.grid(sticky=E, row=4, column=5)
        return

    def K8(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Toni Kroos')
        self.top.l1K8 = Label(self.top, text='Name: Toni Kroos')
        self.top.l1K8.grid(sticky=N, row=0, column=2)
        self.top.l2K8 = Label(self.top, text='Place of birth: Greifswald, Germany')
        self.top.l2K8.grid(sticky=W, row=2, column=1)
        self.top.l3K8 = Label(self.top, text='Date of birth: 04/01/1990')
        self.top.l3K8.grid(sticky=W, row=3, column=1)
        self.top.l4K8 = Label(self.top, text='Age: ' + str(Age(1990, 1, 4)))
        self.top.l4K8.grid(sticky=W, row=4, column=1)
        self.top.l5K8 = Label(self.top, text='Team member since 2014')
        self.top.l5K8.grid(sticky=W, row=5, column=1)
        self.top.l6K8 = Label(self.top, text='Height: 1.83 m')
        self.top.l6K8.grid(sticky=W, row=2, column=3)
        self.top.l7K8 = Label(self.top, text='Weight: 76 kg')
        self.top.l7K8.grid(sticky=W, row=3, column=3)
        self.top.l8K8 = Label(self.top, text='Number: 8')
        self.top.l8K8.grid(sticky=W, row=4, column=3)
        self.top.l9K8 = Label(self.top, text='Position: midfielder')
        self.top.l9K8.grid(sticky=W, row=5, column=3)
        self.top.l10K8 = Label(self.top, text='                       ')
        self.top.l10K8.grid(sticky=W, row=0, column=4)
        self.top.b1K8 = Button(self.top, text='Statistics', command=self.StatK8)
        self.top.b1K8.grid(sticky=E, row=1, column=5)
        self.top.bK8povr = Button(self.top, text='Back', command=self.Back)
        self.top.bK8povr.grid(sticky=W, row=1, column=1)
        return

    def StatK8(self):
        self.top.l1SK8 = Label(self.top, text='Appearances: 33')
        self.top.l1SK8.grid(sticky=E, row=2, column=5)
        self.top.l2SK8 = Label(self.top, text='Goals: 5')
        self.top.l2SK8.grid(sticky=E, row=3, column=5)
        self.top.l3SK8 = Label(self.top, text='Assistance: 7')
        self.top.l3SK8.grid(sticky=E, row=4, column=5)
        return

    def M10(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Luka Modrić')
        self.top.l1M10 = Label(self.top, text='Name: Luka Modrić')
        self.top.l1M10.grid(sticky=N, row=0, column=2)
        self.top.l2M10 = Label(self.top, text='Place of birth: Zadar, Croatia')
        self.top.l2M10.grid(sticky=W, row=2, column=1)
        self.top.l3M10 = Label(self.top, text='Date of birth: 09/09/1985')
        self.top.l3M10.grid(sticky=W, row=3, column=1)
        self.top.l4M10 = Label(self.top, text='Age: ' + str(Age(1985, 9, 9)))
        self.top.l4M10.grid(sticky=W, row=4, column=1)
        self.top.l5M10 = Label(self.top, text='Team member since 2012')
        self.top.l5M10.grid(sticky=W, row=5, column=1)
        self.top.l6M10 = Label(self.top, text='Height: 1.72 m')
        self.top.l6M10.grid(sticky=W, row=2, column=3)
        self.top.l7M10 = Label(self.top, text='Weight: 66.2 kg')
        self.top.l7M10.grid(sticky=W, row=3, column=3)
        self.top.l8M10 = Label(self.top, text='Number: 10')
        self.top.l8M10.grid(sticky=W, row=4, column=3)
        self.top.l9M10 = Label(self.top, text='Position: midfielder')
        self.top.l9M10.grid(sticky=W, row=5, column=3)
        self.top.l10M10 = Label(self.top, text='                       ')
        self.top.l10M10.grid(sticky=W, row=0, column=4)
        self.top.b1M10 = Button(self.top, text='Statistics', command=self.StatM10)
        self.top.b1M10.grid(sticky=E, row=1, column=5)
        self.top.bM10povr = Button(self.top, text='Back', command=self.Back)
        self.top.bM10povr.grid(sticky=W, row=1, column=1)
        return

    def StatM10(self):
        self.top.l1SM10 = Label(self.top, text='Appearances: 30')
        self.top.l1SM10.grid(sticky=E, row=2, column=5)
        self.top.l2SM10 = Label(self.top, text='Goals: 5')
        self.top.l2SM10.grid(sticky=E, row=3, column=5)
        self.top.l3SM10 = Label(self.top, text='Assistance: 2')
        self.top.l3SM10.grid(sticky=E, row=4, column=5)
        return

    def C14(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Carlos Henrique Casimiro')
        self.top.l1C14 = Label(self.top, text='Name: Carlos Henrique Casimiro')
        self.top.l1C14.grid(sticky=N, row=0, column=2)
        self.top.l2C14 = Label(self.top, text='Place of birth: Sao Paulo, Brasil')
        self.top.l2C14.grid(sticky=W, row=2, column=1)
        self.top.l3C14 = Label(self.top, text='Date of birth: 23/02/1992')
        self.top.l3C14.grid(sticky=W, row=3, column=1)
        self.top.l4C14 = Label(self.top, text='Age: ' + str(Age(1992, 2, 23)))
        self.top.l4C14.grid(sticky=W, row=4, column=1)
        self.top.l5C14 = Label(self.top, text='Team member since 2013')
        self.top.l5C14.grid(sticky=W, row=5, column=1)
        self.top.l6C14 = Label(self.top, text='Height: 1.85 m')
        self.top.l6C14.grid(sticky=W, row=2, column=3)
        self.top.l7C14 = Label(self.top, text='Weight: 84 kg')
        self.top.l7C14.grid(sticky=W, row=3, column=3)
        self.top.l8C14 = Label(self.top, text='Number: 14')
        self.top.l8C14.grid(sticky=W, row=4, column=3)
        self.top.l9C14 = Label(self.top, text='Position: midfielder')
        self.top.l9C14.grid(sticky=W, row=5, column=3)
        self.top.l10C14 = Label(self.top, text='                       ')
        self.top.l10C14.grid(sticky=W, row=0, column=4)
        self.top.b1C14 = Button(self.top, text='Statistics', command=self.StatC14)
        self.top.b1C14.grid(sticky=E, row=1, column=5)
        self.top.bC14povr = Button(self.top, text='Back', command=self.Back)
        self.top.bC14povr.grid(sticky=W, row=1, column=1)
        return

    def StatC14(self):
        self.top.l1SC14 = Label(self.top, text='Appearances: 35')
        self.top.l1SC14.grid(sticky=E, row=2, column=5)
        self.top.l2SC14 = Label(self.top, text='Goals: 4')
        self.top.l2SC14.grid(sticky=E, row=3, column=5)
        self.top.l3SC14 = Label(self.top, text='Assistance: 2')
        self.top.l3SC14.grid(sticky=E, row=4, column=5)
        return

    def V15(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Valverde')
        self.top.l1V15 = Label(self.top, text='Name: Federico Santiago Valverde Dipetta')
        self.top.l1V15.grid(sticky=N, row=0, column=2)
        self.top.l2V15 = Label(self.top, text='Place of birth: Montevideo, Uruguay')
        self.top.l2V15.grid(sticky=W, row=2, column=1)
        self.top.l3V15 = Label(self.top, text='Date of birth: 22/07/1998')
        self.top.l3V15.grid(sticky=W, row=3, column=1)
        self.top.l4V15 = Label(self.top, text='Age: ' + str(Age(1998, 7, 22)))
        self.top.l4V15.grid(sticky=W, row=4, column=1)
        self.top.l5V15 = Label(self.top, text='Team member since 2018')
        self.top.l5V15.grid(sticky=W, row=5, column=1)
        self.top.l6V15 = Label(self.top, text='Height: 1.82 m')
        self.top.l6V15.grid(sticky=W, row=2, column=3)
        self.top.l7V15 = Label(self.top, text='Weight: 78 kg')
        self.top.l7V15.grid(sticky=W, row=3, column=3)
        self.top.l8V15 = Label(self.top, text='Number: 15')
        self.top.l8V15.grid(sticky=W, row=4, column=3)
        self.top.l9V15 = Label(self.top, text='Position: midfielder')
        self.top.l9V15.grid(sticky=W, row=5, column=3)
        self.top.l10V15 = Label(self.top, text='                       ')
        self.top.l10V15.grid(sticky=W, row=0, column=4)
        self.top.b1V15 = Button(self.top, text='Statistics', command=self.StatV15)
        self.top.b1V15.grid(sticky=E, row=1, column=5)
        self.top.bV15povr = Button(self.top, text='Back', command=self.Back)
        self.top.bV15povr.grid(sticky=W, row=1, column=1)
        return

    def StatV15(self):
        self.top.l1SV15 = Label(self.top, text='Appearances: 32')
        self.top.l1SV15.grid(sticky=E, row=2, column=5)
        self.top.l2SV15 = Label(self.top, text='Goals: 2')
        self.top.l2SV15.grid(sticky=E, row=3, column=5)
        self.top.l3SV15 = Label(self.top, text='Assistance: 4')
        self.top.l3SV15.grid(sticky=E, row=4, column=5)
        return

    def JR16(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('James Rodríguez')
        self.top.l1JR16 = Label(self.top, text='Name: James Rodríguez')
        self.top.l1JR16.grid(sticky=N, row=0, column=2)
        self.top.l2JR16 = Label(self.top, text='Place of birth: Cucuta, Columbia')
        self.top.l2JR16.grid(sticky=W, row=2, column=1)
        self.top.l3JR16 = Label(self.top, text='Date of birth: 12/07/1991')
        self.top.l3JR16.grid(sticky=W, row=3, column=1)
        self.top.l4JR16 = Label(self.top, text='Age: ' + str(Age(1991, 7, 12)))
        self.top.l4JR16.grid(sticky=W, row=4, column=1)
        self.top.l5JR16 = Label(self.top, text='Team member since 2019')
        self.top.l5JR16.grid(sticky=W, row=5, column=1)
        self.top.l6JR16 = Label(self.top, text='Height: 1.80 m')
        self.top.l6JR16.grid(sticky=W, row=2, column=3)
        self.top.l7JR16 = Label(self.top, text='Weight: 75 kg')
        self.top.l7JR16.grid(sticky=W, row=3, column=3)
        self.top.l8JR16 = Label(self.top, text='Number: 16')
        self.top.l8JR16.grid(sticky=W, row=4, column=3)
        self.top.l9JR16 = Label(self.top, text='Position: midfielder')
        self.top.l9JR16.grid(sticky=W, row=5, column=3)
        self.top.l10JR16 = Label(self.top, text='                       ')
        self.top.l10JR16.grid(sticky=W, row=0, column=4)
        self.top.b1JR16 = Button(self.top, text='Statistics', command=self.StatJR16)
        self.top.b1JR16.grid(sticky=E, row=1, column=5)
        self.top.bJR16povr = Button(self.top, text='Back', command=self.Back)
        self.top.bJR16povr.grid(sticky=W, row=1, column=1)
        return

    def StatJR16(self):
        self.top.l1SJR16 = Label(self.top, text='Appearances: 13')
        self.top.l1SJR16.grid(sticky=E, row=2, column=5)
        self.top.l2SJR16 = Label(self.top, text='Goals: 1')
        self.top.l2SJR16.grid(sticky=E, row=3, column=5)
        self.top.l3SJR16 = Label(self.top, text='Assistance: 2')
        self.top.l3SJR16.grid(sticky=E, row=4, column=5)
        return

    def I22(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Isco')
        self.top.l1I22 = Label(self.top, text='Name: Francisco Román Alarcón')
        self.top.l1I22.grid(sticky=N, row=0, column=2)
        self.top.l2I22 = Label(self.top, text='Place of birth: Benalmádena, Spain')
        self.top.l2I22.grid(sticky=W, row=2, column=1)
        self.top.l3I22 = Label(self.top, text='Date of birth: 21/04/1992')
        self.top.l3I22.grid(sticky=W, row=3, column=1)
        self.top.l4I22 = Label(self.top, text='Age: ' + str(Age(1992, 4, 21)))
        self.top.l4I22.grid(sticky=W, row=4, column=1)
        self.top.l5I22 = Label(self.top, text='Team member since 2013')
        self.top.l5I22.grid(sticky=W, row=5, column=1)
        self.top.l6I22 = Label(self.top, text='Height: 1.76 m')
        self.top.l6I22.grid(sticky=W, row=2, column=3)
        self.top.l7I22 = Label(self.top, text='Weight: 79 kg')
        self.top.l7I22.grid(sticky=W, row=3, column=3)
        self.top.l8I22 = Label(self.top, text='Number: 22')
        self.top.l8I22.grid(sticky=W, row=4, column=3)
        self.top.l9I22 = Label(self.top, text='Position: midfielder')
        self.top.l9I22.grid(sticky=W, row=5, column=3)
        self.top.l10I22 = Label(self.top, text='                       ')
        self.top.l10I22.grid(sticky=W, row=0, column=4)
        self.top.b1I22 = Button(self.top, text='Statistics', command=self.StatI22)
        self.top.b1I22.grid(sticky=E, row=1, column=5)
        self.top.bI22povr = Button(self.top, text='Back', command=self.Back)
        self.top.bI22povr.grid(sticky=W, row=1, column=1)
        return

    def StatI22(self):
        self.top.l1SI22 = Label(self.top, text='Appearances: 23')
        self.top.l1SI22.grid(sticky=E, row=2, column=5)
        self.top.l2SI22 = Label(self.top, text='Goals: 3')
        self.top.l2SI22.grid(sticky=E, row=3, column=5)
        self.top.l3SI22 = Label(self.top, text='Assistance: 0')
        self.top.l3SI22.grid(sticky=E, row=4, column=5)
        return

    def H7(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Eden Hazard')
        self.top.l1H7 = Label(self.top, text='Name: Eden Hazard')
        self.top.l1H7.grid(sticky=N, row=0, column=2)
        self.top.l2H7 = Label(self.top, text='Place of birth: La Louvière, Belgium')
        self.top.l2H7.grid(sticky=W, row=2, column=1)
        self.top.l3H7 = Label(self.top, text='Date of birth: 07/01/1991')
        self.top.l3H7.grid(sticky=W, row=3, column=1)
        self.top.l4H7 = Label(self.top, text='Age: ' + str(Age(1991, 1, 7)))
        self.top.l4H7.grid(sticky=W, row=4, column=1)
        self.top.l5H7 = Label(self.top, text='Team member since 2019')
        self.top.l5H7.grid(sticky=W, row=5, column=1)
        self.top.l6H7 = Label(self.top, text='Height: 1.75 m')
        self.top.l6H7.grid(sticky=W, row=2, column=3)
        self.top.l7H7 = Label(self.top, text='Weight: 74 kg')
        self.top.l7H7.grid(sticky=W, row=3, column=3)
        self.top.l8H7 = Label(self.top, text='Number: 7')
        self.top.l8H7.grid(sticky=W, row=4, column=3)
        self.top.l9H7 = Label(self.top, text='Position: forward')
        self.top.l9H7.grid(sticky=W, row=5, column=3)
        self.top.l10H7 = Label(self.top, text='                       ')
        self.top.l10H7.grid(sticky=W, row=0, column=4)
        self.top.b1H7 = Button(self.top, text='Statistics', command=self.StatH7)
        self.top.b1H7.grid(sticky=E, row=1, column=5)
        self.top.bH7povr = Button(self.top, text='Back', command=self.Back)
        self.top.bH7povr.grid(sticky=W, row=1, column=1)
        return

    def StatH7(self):
        self.top.l1SH7 = Label(self.top, text='Appearances: 15')
        self.top.l1SH7.grid(sticky=E, row=2, column=5)
        self.top.l2SH7 = Label(self.top, text='Goals: 1')
        self.top.l2SH7.grid(sticky=E, row=3, column=5)
        self.top.l3SH7 = Label(self.top, text='Assistance: 1')
        self.top.l3SH7.grid(sticky=E, row=4, column=5)
        return

    def B9(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Karim Benzema')
        self.top.l1B9 = Label(self.top, text='Name: Karim Benzema')
        self.top.l1B9.grid(sticky=N, row=0, column=2)
        self.top.l2B9 = Label(self.top, text='Place of birth: Lyon, France')
        self.top.l2B9.grid(sticky=W, row=2, column=1)
        self.top.l3B9 = Label(self.top, text='Date of birth: 19/12/1987')
        self.top.l3B9.grid(sticky=W, row=3, column=1)
        self.top.l4B9 = Label(self.top, text='Age: ' + str(Age(1987, 12, 19)))
        self.top.l4B9.grid(sticky=W, row=4, column=1)
        self.top.l5B9 = Label(self.top, text='Team member since 2009')
        self.top.l5B9.grid(sticky=W, row=5, column=1)
        self.top.l6B9 = Label(self.top, text='Height: 1.85 m')
        self.top.l6B9.grid(sticky=W, row=2, column=3)
        self.top.l7B9 = Label(self.top, text='Weight: 81.2 kg')
        self.top.l7B9.grid(sticky=W, row=3, column=3)
        self.top.l8B9 = Label(self.top, text='Number: 9')
        self.top.l8B9.grid(sticky=W, row=4, column=3)
        self.top.l9B9 = Label(self.top, text='Position: forward')
        self.top.l9B9.grid(sticky=W, row=5, column=3)
        self.top.l10B9 = Label(self.top, text='                       ')
        self.top.l10B9.grid(sticky=W, row=0, column=4)
        self.top.b1B9 = Button(self.top, text='Statistics', command=self.StatB9)
        self.top.b1B9.grid(sticky=E, row=1, column=5)
        self.top.bB9povr = Button(self.top, text='Back', command=self.Back)
        self.top.bB9povr.grid(sticky=W, row=1, column=1)
        return

    def StatB9(self):
        self.top.l1SB9 = Label(self.top, text='Appearances: 36')
        self.top.l1SB9.grid(sticky=E, row=2, column=5)
        self.top.l2SB9 = Label(self.top, text='Goals: 19')
        self.top.l2SB9.grid(sticky=E, row=3, column=5)
        self.top.l3SB9 = Label(self.top, text='Assistance: 9')
        self.top.l3SB9.grid(sticky=E, row=4, column=5)
        return

    def B11(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Gareth Bale')
        self.top.l1B11 = Label(self.top, text='Name: Gareth Bale')
        self.top.l1B11.grid(sticky=N, row=0, column=2)
        self.top.l2B11 = Label(self.top, text='Place of birth: Cardiff, Wales')
        self.top.l2B11.grid(sticky=W, row=2, column=1)
        self.top.l3B11 = Label(self.top, text='Date of birth: 16/07/1989')
        self.top.l3B11.grid(sticky=W, row=3, column=1)
        self.top.l4B11 = Label(self.top, text='Age: ' + str(Age(1989, 7, 16)))
        self.top.l4B11.grid(sticky=W, row=4, column=1)
        self.top.l5B11 = Label(self.top, text='Team member since 2013')
        self.top.l5B11.grid(sticky=W, row=5, column=1)
        self.top.l6B11 = Label(self.top, text='Height: 1.85 m')
        self.top.l6B11.grid(sticky=W, row=2, column=3)
        self.top.l7B11 = Label(self.top, text='Weight: 81.8 kg')
        self.top.l7B11.grid(sticky=W, row=3, column=3)
        self.top.l8B11 = Label(self.top, text='Number: 11')
        self.top.l8B11.grid(sticky=W, row=4, column=3)
        self.top.l9B11 = Label(self.top, text='Position: forward')
        self.top.l9B11.grid(sticky=W, row=5, column=3)
        self.top.l10B11 = Label(self.top, text='                       ')
        self.top.l10B11.grid(sticky=W, row=0, column=4)
        self.top.b1B11 = Button(self.top, text='Statistics', command=self.StatB11)
        self.top.b1B11.grid(sticky=E, row=1, column=5)
        self.top.bB11povr = Button(self.top, text='Back', command=self.Back)
        self.top.bB11povr.grid(sticky=W, row=1, column=1)
        return

    def StatB11(self):
        self.top.l1SB11 = Label(self.top, text='Appearances: 18')
        self.top.l1SB11.grid(sticky=E, row=2, column=5)
        self.top.l2SB11 = Label(self.top, text='Goals: 3')
        self.top.l2SB11.grid(sticky=E, row=3, column=5)
        self.top.l3SB11 = Label(self.top, text='Assistance: 2')
        self.top.l3SB11.grid(sticky=E, row=4, column=5)
        return

    def LV17(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Lucas Vázquez Iglesias')
        self.top.l1LV17 = Label(self.top, text='Name: Lucas Vázquez Iglesias')
        self.top.l1LV17.grid(sticky=N, row=0, column=2)
        self.top.l2LV17 = Label(self.top, text='Place of birth: Curtis, Spain')
        self.top.l2LV17.grid(sticky=W, row=2, column=1)
        self.top.l3LV17 = Label(self.top, text='Date of birth: 01/07/1991')
        self.top.l3LV17.grid(sticky=W, row=3, column=1)
        self.top.l4LV17 = Label(self.top, text='Age: ' + str(Age(1989, 7, 1)))
        self.top.l4LV17.grid(sticky=W, row=4, column=1)
        self.top.l5LV17 = Label(self.top, text='Team member since 2015')
        self.top.l5LV17.grid(sticky=W, row=5, column=1)
        self.top.l6LV17 = Label(self.top, text='Height: 1.73 m')
        self.top.l6LV17.grid(sticky=W, row=2, column=3)
        self.top.l7LV17 = Label(self.top, text='Weight: 70.5 kg')
        self.top.l7LV17.grid(sticky=W, row=3, column=3)
        self.top.l8LV17 = Label(self.top, text='Number: 17')
        self.top.l8LV17.grid(sticky=W, row=4, column=3)
        self.top.l9LV17 = Label(self.top, text='Position: forward')
        self.top.l9LV17.grid(sticky=W, row=5, column=3)
        self.top.l10LV17 = Label(self.top, text='                       ')
        self.top.l10LV17.grid(sticky=W, row=0, column=4)
        self.top.b1LV17 = Button(self.top, text='Statistics', command=self.StatLV17)
        self.top.b1LV17.grid(sticky=E, row=1, column=5)
        self.top.bLV17povr = Button(self.top, text='Back', command=self.Back)
        self.top.bLV17povr.grid(sticky=W, row=1, column=1)
        return

    def StatLV17(self):
        self.top.l1SLV17 = Label(self.top, text='Appearances: 18')
        self.top.l1SLV17.grid(sticky=E, row=2, column=5)
        self.top.l2SLV17 = Label(self.top, text='Goals: 3')
        self.top.l2SLV17.grid(sticky=E, row=3, column=5)
        self.top.l3SLV17 = Label(self.top, text='Assistance: 1')
        self.top.l3SLV17.grid(sticky=E, row=4, column=5)
        return

    def J18(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Luka Jović')
        self.top.l1J18 = Label(self.top, text='Name: Luka Jović')
        self.top.l1J18.grid(sticky=N, row=0, column=2)
        self.top.l2J18 = Label(self.top, text='Place of birth: Bijeljina, Bosnia and Herzegovina')
        self.top.l2J18.grid(sticky=W, row=2, column=1)
        self.top.l3J18 = Label(self.top, text='Date of birth: 23/12/1997')
        self.top.l3J18.grid(sticky=W, row=3, column=1)
        self.top.l4J18 = Label(self.top, text='Age: ' + str(Age(1997, 12, 23)))
        self.top.l4J18.grid(sticky=W, row=4, column=1)
        self.top.l5J18 = Label(self.top, text='Team member since 2019')
        self.top.l5J18.grid(sticky=W, row=5, column=1)
        self.top.l6J18 = Label(self.top, text='Height: 1.82 m')
        self.top.l6J18.grid(sticky=W, row=2, column=3)
        self.top.l7J18 = Label(self.top, text='Weight: 85 kg')
        self.top.l7J18.grid(sticky=W, row=3, column=3)
        self.top.l8J18 = Label(self.top, text='Number: 18')
        self.top.l8J18.grid(sticky=W, row=4, column=3)
        self.top.l9J18 = Label(self.top, text='Position: forward')
        self.top.l9J18.grid(sticky=W, row=5, column=3)
        self.top.l10J18 = Label(self.top, text='                       ')
        self.top.l10J18.grid(sticky=W, row=0, column=4)
        self.top.b1J18 = Button(self.top, text='Statistics', command=self.StatJ18)
        self.top.b1J18.grid(sticky=E, row=1, column=5)
        self.top.bJ18povr = Button(self.top, text='Back', command=self.Back)
        self.top.bJ18povr.grid(sticky=W, row=1, column=1)
        return

    def StatJ18(self):
        self.top.l1SJ18 = Label(self.top, text='Appearances: 24')
        self.top.l1SJ18.grid(sticky=E, row=2, column=5)
        self.top.l2SJ18 = Label(self.top, text='Goals: 2')
        self.top.l2SJ18.grid(sticky=E, row=3, column=5)
        self.top.l3SJ18 = Label(self.top, text='Assistance: 1')
        self.top.l3SJ18.grid(sticky=E, row=4, column=5)
        return

    def A20(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Marco Asensio Willemsen')
        self.top.l1A20 = Label(self.top, text='Name: Marco Asensio Willemsen')
        self.top.l1A20.grid(sticky=N, row=0, column=2)
        self.top.l2A20 = Label(self.top, text='Place of birth: Palma de Mallorca')
        self.top.l2A20.grid(sticky=W, row=2, column=1)
        self.top.l3A20 = Label(self.top, text='Date of birth: 21/01/1996')
        self.top.l3A20.grid(sticky=W, row=3, column=1)
        self.top.l4A20 = Label(self.top, text='Age: ' + str(Age(1996, 21, 1)))
        self.top.l4A20.grid(sticky=W, row=4, column=1)
        self.top.l5A20 = Label(self.top, text='Team member since 2016')
        self.top.l5A20.grid(sticky=W, row=5, column=1)
        self.top.l6A20 = Label(self.top, text='Height: 1.82 m')
        self.top.l6A20.grid(sticky=W, row=2, column=3)
        self.top.l7A20 = Label(self.top, text='Weight: 76 kg')
        self.top.l7A20.grid(sticky=W, row=3, column=3)
        self.top.l8A20 = Label(self.top, text='Number: 20')
        self.top.l8A20.grid(sticky=W, row=4, column=3)
        self.top.l9A20 = Label(self.top, text='Position: forward')
        self.top.l9A20.grid(sticky=W, row=5, column=3)
        self.top.l10A20 = Label(self.top, text='                       ')
        self.top.l10A20.grid(sticky=W, row=0, column=4)
        self.top.b1A20 = Button(self.top, text='Statistics', command=self.StatA20)
        self.top.b1A20.grid(sticky=E, row=1, column=5)
        self.top.bA20povr = Button(self.top, text='Back', command=self.Back)
        self.top.bA20povr.grid(sticky=W, row=1, column=1)
        return

    def StatA20(self):
        self.top.l1SA20 = Label(self.top, text='Appearances: 0')
        self.top.l1SA20.grid(sticky=E, row=2, column=5)
        self.top.l2SA20 = Label(self.top, text='Goals: 0')
        self.top.l2SA20.grid(sticky=E, row=3, column=5)
        self.top.l3SA20 = Label(self.top, text='Assistance: 0')
        self.top.l3SA20.grid(sticky=E, row=4, column=5)
        return

    def B21(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Brahim Díaz')
        self.top.l1B21 = Label(self.top, text='Name: Brahim Díaz')
        self.top.l1B21.grid(sticky=N, row=0, column=2)
        self.top.l2B21 = Label(self.top, text='Place of birth: Malaga')
        self.top.l2B21.grid(sticky=W, row=2, column=1)
        self.top.l3B21 = Label(self.top, text='Date of birth: 03/08/1999')
        self.top.l3B21.grid(sticky=W, row=3, column=1)
        self.top.l4B21 = Label(self.top, text='Age: ' + str(Age(1999, 8, 3)))
        self.top.l4B21.grid(sticky=W, row=4, column=1)
        self.top.l5B21 = Label(self.top, text='Team member since 2019')
        self.top.l5B21.grid(sticky=W, row=5, column=1)
        self.top.l6B21 = Label(self.top, text='Height: 1.71 m')
        self.top.l6B21.grid(sticky=W, row=2, column=3)
        self.top.l7B21 = Label(self.top, text='Weight: 68 kg')
        self.top.l7B21.grid(sticky=W, row=3, column=3)
        self.top.l8B21 = Label(self.top, text='Number: 21')
        self.top.l8B21.grid(sticky=W, row=4, column=3)
        self.top.l9B21 = Label(self.top, text='Position: forward')
        self.top.l9B21.grid(sticky=W, row=5, column=3)
        self.top.l10B21 = Label(self.top, text='                       ')
        self.top.l10B21.grid(sticky=W, row=0, column=4)
        self.top.b1B21 = Button(self.top, text='Statistics', command=self.StatB21)
        self.top.b1B21.grid(sticky=E, row=1, column=5)
        self.top.bB21povr = Button(self.top, text='Back', command=self.Back)
        self.top.bB21povr.grid(sticky=W, row=1, column=1)
        return

    def StatB21(self):
        self.top.l1SB21 = Label(self.top, text='Appearances: 7')
        self.top.l1SB21.grid(sticky=E, row=2, column=5)
        self.top.l2SB21 = Label(self.top, text='Goals: 1')
        self.top.l2SB21.grid(sticky=E, row=3, column=5)
        self.top.l3SB21 = Label(self.top, text='Assistance: 1')
        self.top.l3SB21.grid(sticky=E, row=4, column=5)
        return

    def M24(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Mariano Díaz Mejía')
        self.top.l1M24 = Label(self.top, text='Name: Mariano Díaz Mejía')
        self.top.l1M24.grid(sticky=N, row=0, column=2)
        self.top.l2M24 = Label(self.top, text='Place of birth: Barcelona, Spain')
        self.top.l2M24.grid(sticky=W, row=2, column=1)
        self.top.l3M24 = Label(self.top, text='Date of birth: 01/08/1993')
        self.top.l3M24.grid(sticky=W, row=3, column=1)
        self.top.l4M24 = Label(self.top, text='Age: ' + str(Age(1993, 8, 1)))
        self.top.l4M24.grid(sticky=W, row=4, column=1)
        self.top.l5M24 = Label(self.top, text='Team member since 2018')
        self.top.l5M24.grid(sticky=W, row=5, column=1)
        self.top.l6M24 = Label(self.top, text='Height: 1.80 m')
        self.top.l6M24.grid(sticky=W, row=2, column=3)
        self.top.l7M24 = Label(self.top, text='Weight: 76 kg')
        self.top.l7M24.grid(sticky=W, row=3, column=3)
        self.top.l8M24 = Label(self.top, text='Number: 24')
        self.top.l8M24.grid(sticky=W, row=4, column=3)
        self.top.l9M24 = Label(self.top, text='Position: forward')
        self.top.l9M24.grid(sticky=W, row=5, column=3)
        self.top.l10M24 = Label(self.top, text='                       ')
        self.top.l10M24.grid(sticky=W, row=0, column=4)
        self.top.b1M24 = Button(self.top, text='Statistics', command=self.StatM24)
        self.top.b1M24.grid(sticky=E, row=1, column=5)
        self.top.bM24povr = Button(self.top, text='Back', command=self.Back)
        self.top.bM24povr.grid(sticky=W, row=1, column=1)
        return

    def StatM24(self):
        self.top.l1SM24 = Label(self.top, text='Appearances: 4')
        self.top.l1SM24.grid(sticky=E, row=2, column=5)
        self.top.l2SM24 = Label(self.top, text='Goals: 1')
        self.top.l2SM24.grid(sticky=E, row=3, column=5)
        self.top.l3SM24 = Label(self.top, text='Assistance: 0')
        self.top.l3SM24.grid(sticky=E, row=4, column=5)
        return

    def VJ25(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Vinicius Junior')
        self.top.l1VJ25 = Label(self.top, text='Name: Vinicius Paixao de Oliveira Junior')
        self.top.l1VJ25.grid(sticky=N, row=0, column=2)
        self.top.l2VJ25 = Label(self.top, text='Place of birth: Rio de Janeiro, Brasil')
        self.top.l2VJ25.grid(sticky=W, row=2, column=1)
        self.top.l3VJ25 = Label(self.top, text='Date of birth: 12/07/2000')
        self.top.l3VJ25.grid(sticky=W, row=3, column=1)
        self.top.l4VJ25 = Label(self.top, text='Age: ' + str(Age(2000, 7, 12)))
        self.top.l4VJ25.grid(sticky=W, row=4, column=1)
        self.top.l5VJ25 = Label(self.top, text='Team member since 2018')
        self.top.l5VJ25.grid(sticky=W, row=5, column=1)
        self.top.l6VJ25 = Label(self.top, text='Height: 1.76 m')
        self.top.l6VJ25.grid(sticky=W, row=2, column=3)
        self.top.l7VJ25 = Label(self.top, text='Weight: 73 kg')
        self.top.l7VJ25.grid(sticky=W, row=3, column=3)
        self.top.l8VJ25 = Label(self.top, text='Number: 25')
        self.top.l8VJ25.grid(sticky=W, row=4, column=3)
        self.top.l9VJ25 = Label(self.top, text='Position: forward')
        self.top.l9VJ25.grid(sticky=W, row=5, column=3)
        self.top.l10VJ25 = Label(self.top, text='                       ')
        self.top.l10VJ25.grid(sticky=W, row=0, column=4)
        self.top.b1VJ25 = Button(self.top, text='Statistics', command=self.StatVJ25)
        self.top.b1VJ25.grid(sticky=E, row=1, column=5)
        self.top.bVJ25povr = Button(self.top, text='Back', command=self.Back)
        self.top.bVJ25povr.grid(sticky=W, row=1, column=1)
        return

    def StatVJ25(self):
        self.top.l1SVJ25 = Label(self.top, text='Appearances: 28')
        self.top.l1SVJ25.grid(sticky=E, row=2, column=5)
        self.top.l2SVJ25 = Label(self.top, text='Goals: 4')
        self.top.l2SVJ25.grid(sticky=E, row=3, column=5)
        self.top.l3SVJ25 = Label(self.top, text='Assistance: 3')
        self.top.l3SVJ25.grid(sticky=E, row=4, column=5)
        return

    def R27(self):
        self.top.destroy()
        self.top = Toplevel()
        self.top.title('Rodrygo Goes')
        self.top.l1R27 = Label(self.top, text='Name: Rodrygo Goes')
        self.top.l1R27.grid(sticky=N, row=0, column=2)
        self.top.l2R27 = Label(self.top, text='Place of birth: Osasco, Brasil')
        self.top.l2R27.grid(sticky=W, row=2, column=1)
        self.top.l3R27 = Label(self.top, text='Date of birth: 09/01/2001.')
        self.top.l3R27.grid(sticky=W, row=3, column=1)
        self.top.l4R27 = Label(self.top, text='Age: ' + str(Age(2001, 1, 9)))
        self.top.l4R27.grid(sticky=W, row=4, column=1)
        self.top.l5R27 = Label(self.top, text='Team member since 2019.')
        self.top.l5R27.grid(sticky=W, row=5, column=1)
        self.top.l6R27 = Label(self.top, text='Height: 1.74 m')
        self.top.l6R27.grid(sticky=W, row=2, column=3)
        self.top.l7R27 = Label(self.top, text='Weight: 64 kg')
        self.top.l7R27.grid(sticky=W, row=3, column=3)
        self.top.l8R27 = Label(self.top, text='Number: 27')
        self.top.l8R27.grid(sticky=W, row=4, column=3)
        self.top.l9R27 = Label(self.top, text='Position: forward')
        self.top.l9R27.grid(sticky=W, row=5, column=3)
        self.top.l10R27 = Label(self.top, text='                       ')
        self.top.l10R27.grid(sticky=W, row=0, column=4)
        self.top.b1R27 = Button(self.top, text='Statistics', command=self.StatR27)
        self.top.b1R27.grid(sticky=E, row=1, column=5)
        self.top.bR27povr = Button(self.top, text='Back', command=self.Back)
        self.top.bR27povr.grid(sticky=W, row=1, column=1)
        return

    def StatR27(self):
        self.top.l1SR27 = Label(self.top, text='Appearances: 18')
        self.top.l1SR27.grid(sticky=E, row=2, column=5)
        self.top.l2SR27 = Label(self.top, text='Goals: 7')
        self.top.l2SR27.grid(sticky=E, row=3, column=5)
        self.top.l3SR27 = Label(self.top, text='Assistance: 1')
        self.top.l3SR27.grid(sticky=E, row=4, column=5)
        return

    def Find(self):
        x=self.top.e1pret.get().title()
        self.top.l1nadi.config(text='')
        if x == 'Alphonse Areola' or x == 'Alphonse' or x == 'Areola':
            self.top.b1nadi = Button(self.top, text='Areola', command=self.A1)
            self.top.b1nadi.grid(row=1, column=3)
        elif x == 'Thibaut Courtois' or x == 'Thibaut' or x == 'Courtois':
            self.top.b1nadi = Button(self.top, text='Courtois', command=self.C13)
            self.top.b1nadi.grid(row=1, column=3)
        elif 'Daniel' in x or 'Carvajal' in x:
            self.top.b1nadi = Button(self.top, text='Carvajal', command=self.C2)
            self.top.b1nadi.grid(row=1, column=3)
        elif 'Eder' in x or 'Gabriel' in x or 'Militao' in x or 'Éder' in x or 'Militão' in x:
            self.top.b1nadi = Button(self.top, text='E. Militão', command=self.M3)
            self.top.b1nadi.grid(row=1, column=3)
        elif 'Sergio' in x or 'Ramos' in x or 'García' in x or 'Garcia' in x:
            self.top.b1nadi = Button(self.top, text='Sergio Ramos', command=self.SR4)
            self.top.b1nadi.grid(row=1, column=3)
        elif 'Raphaël' in x or 'Raphael' in x or 'Varane' in x:
            self.top.b1nadi = Button(self.top, text='R. Varane', command=self.V5)
            self.top.b1nadi.grid(row=1, column=3)
        elif 'Nacho' in x or 'Fernández' in x or 'Fernandez' in x or 'Fernandez Iglesias' in x or 'Fernández Inglesias' in x:
            self.top.b1nadi = Button(self.top, text='Nacho', command=self.N6)
            self.top.b1nadi.grid(row=1, column=3)
        elif 'Marcelo' in x or 'Vieira' in x or 'da Silva' in x:
            self.top.b1nadi = Button(self.top, text='Marcelo', command=self.M12)
            self.top.b1nadi.grid(row=1, column=3)
        elif 'Ferland' in x or 'Mendy' in x:
            self.top.b1nadi = Button(self.top, text='F. Mendy', command=self.M23)
            self.top.b1nadi.grid(row=1, column=3)
        elif 'Toni' in x or 'Kroos' in x:
            self.top.b1nadi = Button(self.top, text='Kroos', command=self.K8)
            self.top.b1nadi.grid(row=1, column=3)
        elif 'Luka Modrić' in x or 'Modrić' in x or 'Luka Modric' in x or 'Modric' in x:
            self.top.b1nadi = Button(self.top, text='Modrić', command=self.M10)
            self.top.b1nadi.grid(row=1, column=3)
        elif 'Casemiro' in x or 'Carlos' in x or 'Henrique' in x or 'Casimiro' in x:
            self.top.b1nadi = Button(self.top, text='Casemiro', command=self.C14)
            self.top.b1nadi.grid(row=1, column=3)
        elif 'Federico' in x or 'Santiago' in x or 'Valverde' in x or 'Dipetta' in x:
            self.top.b1nadi = Button(self.top, text='Valverde', command=self.V15)
            self.top.b1nadi.grid(row=1, column=3)
        elif 'James' in x or 'Rodríguez' in x or 'Rodriguez' in x:
            self.top.b1nadi = Button(self.top, text='James Rodríguez', command=self.JR16)
            self.top.b1nadi.grid(row=1, column=3)
        elif 'Francisco' in x or 'Román' in x or 'Alarcón' in x or 'Isco' in x or 'Roman' in x or 'Alarcon' in x:
            self.top.b1nadi = Button(self.top, text='Isco', command=self.I22)
            self.top.b1nadi.grid(row=1, column=3)
        elif 'Eden' in x or 'Hazard' in x:
            self.top.b1nadi = Button(self.top, text='Hazard', command=self.H7)
            self.top.b1nadi.grid(row=1, column=3)
        elif 'Karim' in x or 'Benzema' in x:
            self.top.b1nadi = Button(self.top, text='Benzema', command=self.B9)
            self.top.b1nadi.grid(row=1, column=3)
        elif 'Gareth' in x or 'Bale' in x:
            self.top.b1nadi = Button(self.top, text='Bale', command=self.B11)
            self.top.b1nadi.grid(row=1, column=3)
        elif 'Lucas' in x or 'Vázquez' in x or 'Vazquez' in x or 'Lucas Iglesias' in x or 'Vázquez Iglesias' in x or 'Vazquez Inglesias' in x:
            self.top.b1nadi = Button(self.top, text='Lucas Vázquez', command=self.LV17)
            self.top.b1nadi.grid(row=1, column=3)
        elif 'Luka Jović' in x or 'Jović' in x:
            self.top.b1nadi = Button(self.top, text='Jović', command=self.J18)
            self.top.b1nadi.grid(row=1, column=3)
        elif 'Marco' in x or 'Asensio' in x or 'Willemsen' in x:
            self.top.b1nadi = Button(self.top, text='Asensio', command=self.A20)
            self.top.b1nadi.grid(row=1, column=3)
        elif 'Brahim' in x or 'Brahim Díaz' in x or 'Brahim Diaz' in x:
            self.top.b1nadi = Button(self.top, text='Brahim', command=self.B21)
            self.top.b1nadi.grid(row=1, column=3)
        elif 'Mariano' in x or 'Mariano Díaz' in x or 'Mariano Diaz' in x or 'Mejía' in x or 'Mejia' in x:
            self.top.b1nadi = Button(self.top, text='Mariano', command=self.M24)
            self.top.b1nadi.grid(row=1, column=3)
        elif 'Vinicius' in x or 'Paixao' in x or 'de Oliveira' in x or 'Junior' in x:
            self.top.b1nadi = Button(self.top, text='Vinicius Junior', command=self.VJ25)
            self.top.b1nadi.grid(row=1, column=3)
        elif 'Rodrygo' in x or 'Goes' in x:
            self.top.b1nadi = Button(self.top, text='Rodrygo', command=self.R27)
            self.top.b1nadi.grid(row=1, column=3)
        else:
            self.top.l1nadi.config(text='There is no current player with this name.')
        return
    
t = Tk()
app = App(t)
t.mainloop()
